name: Build Mod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore LoveCharmBabyMod.csproj

    - name: Build the mod
      run: msbuild LoveCharmBabyMod.csproj /p:Configuration=Release

    - name: Upload mod
      uses: actions/upload-artifact@v4
      with:
        name: LoveCharmBabyMod
        path: bin/Release/*.dll
        
