name: Build Mod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Build the mod
      run: |
        msbuild LoveCharmBabyMod.csproj /p:Configuration=Release
    - name: Upload mod
      uses: actions/upload-artifact@v3
      with:
        name: LoveCharmBabyMod
        path: bin/Release/*.dll
        
