name: Build Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Display lib folder (debugging)
        run: dir lib
        working-directory: LoveCharmBabyMod

      - name: Build the mod
        run: msbuild LoveCharmBabyMod.csproj /p:Configuration=Release
        working-directory: LoveCharmBabyMod

      - name: Upload mod DLL
        uses: actions/upload-artifact@v4
        with:
          name: LoveCharmBabyMod
          path: LoveCharmBabyMod/bin/Release/LoveCharmBabyMod.dll
          
